[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
image = "0.23"
indicatif = "0.17.5"
rayon = "1.7.0"
tobj = "4.0.0"
